### ISSUE TITLE
4.27 issue

### ISSUE THREAD

**Issue by haaranoos** [Ares9323/Restart-Unreal-Engine-Editor-Plugin#2]
Thank you very much for this.
unfortunally 4.27 version gives error when loading and complaining about this is compiled for other engin version.

**Comment by Ares9323** [comment]
Thanks for the report, I compiled this (and tested it) when 4.27 was still in beta, maybe something changed in the final release!

Unfortunately I don't have the latest 4.27 downloaded, I'll update this ASAP

**Comment by Ares9323** [comment]
Hi, I recompiled and tested with the latest 4.27 and now it works for me, tell me if it works for you too so I can close the issue 😊

**Comment by haaranoos** [comment]
working great!
thank you very much.
